### ISSUE TITLE
Build the web version of linon panicked on win11

### ISSUE THREAD

**Issue by SunOfHomeBoy** [niklaskorz/linon#3]
![image](https://github.com/niklaskorz/linon/assets/30047595/724ff71e-a7bb-491a-be55-e3b1a724ad2e)
![image](https://github.com/niklaskorz/linon/assets/30047595/c2466024-49fd-4069-884b-d6b95eb40c82)

Following the README document, the first three steps are all correct. It wasn't until step four that I had a problem!

![image](https://github.com/niklaskorz/linon/assets/30047595/cfe7ed70-15a4-4852-a2f7-860bdf3a5ec6)

**Comment by niklaskorz** [comment]
Linon is currently built with wasm-bindgen-cli 0.2.84, not 0.2.77, I will update the README accordingly. :)

From the [Github actions workflow](https://github.com/niklaskorz/linon/blob/main/.github/workflows/CICD.yml):

```
cargo install -f wasm-bindgen-cli --version 0.2.84
RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build --target wasm32-unknown-unknown --release
wasm-bindgen --out-dir public --web target/wasm32-unknown-unknown/release/linon.wasm
```

Does this work for you?

**Comment by SunOfHomeBoy** [comment]
> 

Ok, thank you very much. Problem solved! 👍
![image](https://github.com/niklaskorz/linon/assets/30047595/6e281a86-d069-4206-82e6-2f05eb47c69c)
